language: ruby
cache: bundler
dist: xenial

bundler_args: --without guard, changelog

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.9
    - rvm: 2.5.7
    - rvm: 2.6.5
    - rvm: 2.7.0
    - rvm: ruby-head
  allow_failures:
  - rvm: ruby-head

branches:
  only:
    - master

addons:
  code_climate:
    repo_token:
      secure: "jVI7J+yiQcD5T1YNz9eGReGf6vyp8VIGjsyMEM0HBOxrbk4iCm7P5SN5n5cJPRZNzQd175ceqcpPisvJh91oPMetzpmN+PSDPhOzxVNB4rIqQ8ohJNX2jW/VVpaobzWHAQQurC349gfi2a6l7MvgZw3RGyExkacZXdqr+Bbsc38="
